import type { Capabilities, SidebarMenuByRole, SidebarMenuEntry } from '../../types';
import type { UserRole } from '../../types/auth';

export function sidebarMenu(role: UserRole | null | undefined, capabilities: Capabilities = { has_wali_kelas: false }): SidebarMenuEntry[] {
    const menus: SidebarMenuByRole = {
        guru: [section('Dashboard'), item('Beranda','/guru/dashboard','bi-house-heart-fill',['/guru/dashboard'],true), section('Kelola Data'), item('Kelas','/admin/kelas','bi-building',['/admin/kelas'],true), item('Kelas & Siswa','/admin/kelas-siswa','bi-mortarboard-fill',['/admin/kelas-siswa'],true), section('Pembelajaran'), item('Materi','/guru/materi','bi-file-earmark-text-fill',['/guru/materi'],true), item('Tugas','/guru/tugas','bi-journal-check',['/guru/tugas'],true), item('Nilai','/guru/nilai','bi-bar-chart-fill',['/guru/nilai'],true), item('Sikap','/guru/sikap','bi-emoji-smile-fill',['/guru/sikap'],true), item('Absensi','/guru/absensi','bi-clipboard-check-fill',['/guru/absensi'],true), section('Pengaturan'), item('Mata Pelajaran','/admin/mata-pelajaran','bi-book-fill',['/admin/mata-pelajaran'],true), item('Tahun Ajaran','/admin/tahun-ajaran','bi-calendar-event-fill',['/admin/tahun-ajaran'],true), item('Pengaturan Sekolah','/admin/pengaturan','bi-gear-fill',['/admin/pengaturan'],true), ...(capabilities.has_wali_kelas ? [section('Wali Kelas'), item('Wali Kelas','/guru/wali-kelas','bi-person-badge-fill',['/guru/wali-kelas'],true)] : []), section('Komunikasi'), item('Kelas Daring','/guru/kelas-daring','bi-camera-video-fill',['/guru/kelas-daring'],true), item('Kalender','/guru/kalender','bi-calendar3',['/guru/kalender'],true), item('Pengumuman','/guru/pengumuman','bi-megaphone-fill',['/guru/pengumuman'],true), item('Chat Kelas','/guru/chat','bi-chat-dots-fill',['/guru/chat'],true), section('Rekap'), item('Rekap Absensi','/guru/rekap-absensi','bi-file-earmark-spreadsheet-fill',['/guru/rekap-absensi'],true), item('Rekap Nilai','/guru/rekap-nilai','bi-file-earmark-bar-graph-fill',['/guru/rekap-nilai']), item('Rekap Sikap','/guru/rekap-sikap','bi-file-earmark-text-fill',['/guru/rekap-sikap']), section('Akun'), item('Pengaturan Akun','/guru/pengaturan','bi-person-gear',['/guru/pengaturan','/guru/profil'],true)],
        siswa: [section('Belajar'), item('Dashboard','/siswa/dashboard','bi-speedometer2',['/siswa/dashboard'],true), item('Jadwal Pelajaran','/siswa/jadwal-pelajaran','bi-calendar-week-fill',['/siswa/jadwal-pelajaran'],true), item('Kelas Daring','/siswa/kelas-daring','bi-camera-video-fill',['/siswa/kelas-daring'],true), item('Progress Saya','/siswa/progress','bi-graph-up-arrow',['/siswa/progress'],true), item('Materi Saya','/siswa/materi','bi-file-earmark-text-fill',['/siswa/materi'],true), item('Tugas Saya','/siswa/tugas','bi-journal-check',['/siswa/tugas'],true), item('Nilai Saya','/siswa/nilai','bi-bar-chart-fill',['/siswa/nilai'],true), section('Kelas'), item('Kalender','/siswa/kalender','bi-calendar3',['/siswa/kalender'],true), item('Pengumuman','/siswa/pengumuman','bi-megaphone-fill',['/siswa/pengumuman'],true), item('Chat Kelas','/siswa/chat','bi-chat-dots-fill',['/siswa/chat'],true), section('Akun'), item('Pengaturan','/siswa/pengaturan','bi-person-gear',['/siswa/pengaturan','/siswa/profil'],true)],
    }; return role ? menus[role] ?? [] : [];
}
function section(label: string): SidebarMenuEntry { return { type: 'section', label }; }
function item(label: string, href: string, icon: string, activePrefixes: string[], inertia = false): SidebarMenuEntry { return { type: 'item', label, href, icon, activePrefixes, inertia }; }
